name: Tests

on:
  pull_requests:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    tests:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        uses: npm ci


      - name: Run tests and enforce coverage
        uses: npm run test:coverage

      - name: Validate coverage report
        uses: test -s coveage/lcov.info